# Generated by Django 6.0.1 on 2026-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_date_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
